@php
    $wilayah = request()->routeIs('cluster_usaha.*', 'kube.*', 'pendamping.*'); $monev = request()->routeIs('monitoring.*', 'laporan.*', 'kunjungan.*', 'perkembangan.*', 'bimbingan.*', 'pelatihan.*'); $laporan = request()->routeIs('ranking.kube*', 'rekap_kube.*');
    $active = 'bg-indigo-800 text-white shadow-inner'; $inactive = 'text-indigo-100 hover:bg-indigo-600 hover:text-white'; $subActive = 'bg-indigo-700 text-white border-l-2 border-white'; $subInactive = 'text-indigo-200 hover:bg-indigo-700/60 hover:text-white';
@endphp
<nav class="flex-1 px-4 mt-4 space-y-2 overflow-y-auto custom-scrollbar">
    <a href="{{ route('koordinator.dashboard') }}" class="flex items-center gap-3 px-4 py-3 rounded-xl transition-all {{ request()->routeIs('koordinator.dashboard', 'dashboard.koordinator') ? 'bg-indigo-800 text-white border-l-4 border-white shadow-inner' : $inactive }}"><i data-lucide="layout-grid" class="w-5 h-5"></i><span class="font-medium">Dashboard Wilayah</span></a>
    <div class="relative"><button type="button" onclick="toggleDropdown('wilayahMenu', 'wilayahIcon')" class="w-full flex items-center justify-between px-4 py-3 rounded-xl transition-all {{ $wilayah ? $active : $inactive }}"><span class="flex items-center gap-3"><i data-lucide="map" class="w-5 h-5"></i><span class="font-medium text-sm">Manajemen Wilayah</span></span><i data-lucide="chevron-down" id="wilayahIcon" class="w-4 h-4 transition-transform {{ $wilayah ? 'rotate-180' : '' }}"></i></button><div id="wilayahMenu" class="{{ $wilayah ? '' : 'hidden' }} flex flex-col mt-2 ml-4 space-y-1 border-l border-indigo-500/50 pl-4 text-[11px] uppercase tracking-widest font-bold"><a href="{{ route('cluster_usaha.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('cluster_usaha.*') ? $subActive : $subInactive }}">Data Cluster Usaha</a><a href="{{ route('kube.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('kube.*') ? $subActive : $subInactive }}">Daftar KUBE Binaan</a><a href="{{ route('pendamping.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('pendamping.*') ? $subActive : $subInactive }}">Data Pendamping</a></div></div>
    <div class="relative"><button type="button" onclick="toggleDropdown('monevMenu', 'monevIcon')" class="w-full flex items-center justify-between px-4 py-3 rounded-xl transition-all {{ $monev ? $active : $inactive }}"><span class="flex items-center gap-3"><i data-lucide="activity" class="w-5 h-5"></i><span class="font-medium text-sm">Monev & Bimbingan</span></span><i data-lucide="chevron-down" id="monevIcon" class="w-4 h-4 transition-transform {{ $monev ? 'rotate-180' : '' }}"></i></button><div id="monevMenu" class="{{ $monev ? '' : 'hidden' }} flex flex-col mt-2 ml-4 space-y-1 border-l border-indigo-500/50 pl-4 text-[11px] uppercase tracking-widest font-bold"><a href="{{ route('monitoring.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('monitoring.*') ? $subActive : $subInactive }}">Monitoring Bantuan</a>
                
        <a href="{{ route('kunjungan.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('kunjungan.*') ? $subActive : $subInactive }}">Kunjungan</a><a href="{{ route('perkembangan.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('perkembangan.*') ? $subActive : $subInactive }}">Perkembangan Usaha</a><a href="{{ route('bimbingan.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('bimbingan.*') ? $subActive : $subInactive }}">Bimbingan</a><a href="{{ route('pelatihan.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('pelatihan.*') ? $subActive : $subInactive }}">Pelatihan KUBE</a></div></div>
    <div class="relative"><button type="button" onclick="toggleDropdown('analisisKoordMenu', 'analisisKoordIcon')" class="w-full flex items-center justify-between px-4 py-3 rounded-xl transition-all {{ $laporan ? $active : $inactive }}"><span class="flex items-center gap-3"><i data-lucide="pie-chart" class="w-5 h-5"></i><span class="font-medium text-sm">Laporan Akhir</span></span><i data-lucide="chevron-down" id="analisisKoordIcon" class="w-4 h-4 transition-transform {{ $laporan ? 'rotate-180' : '' }}"></i></button><div id="analisisKoordMenu" class="{{ $laporan ? '' : 'hidden' }} flex flex-col mt-2 ml-4 space-y-1 border-l border-indigo-500/50 pl-4 text-[11px] uppercase tracking-widest font-bold"><a href="{{ route('ranking.kube') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('ranking.kube*') ? $subActive : $subInactive }}">Ranking KUBE Kecamatan</a><a href="{{ route('rekap_kube.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('rekap_kube.*') ? $subActive : $subInactive }}">Rekap KUBE Aktif/Vakum</a></div></div>
</nav>
