<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('desa_kelurahan', function (Blueprint $table) {
            $table->id('id_desa_kelurahan');
            $table->string('nama_desa_kelurahan', 100);
            $table->unsignedBigInteger('id_kecamatan');
            
            // Biar otomatis keisi pas pake DB::table()->insert()
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent()->useCurrentOnUpdate();

            $table->foreign('id_kecamatan')
                ->references('id_kecamatan')
                ->on('kecamatan')
                ->onDelete('cascade')
                ->onUpdate('cascade');
        });

        DB::table('desa_kelurahan')->insert([
            ['id_desa_kelurahan' => 1, 'nama_desa_kelurahan' => 'Adipala', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 2, 'nama_desa_kelurahan' => 'Adiraja', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 3, 'nama_desa_kelurahan' => 'Adireja Kulon', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 4, 'nama_desa_kelurahan' => 'Adireja Wetan', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 5, 'nama_desa_kelurahan' => 'Bunton', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 6, 'nama_desa_kelurahan' => 'Doplang', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 7, 'nama_desa_kelurahan' => 'Glempangpasir', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 8, 'nama_desa_kelurahan' => 'Gombolharjo', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 9, 'nama_desa_kelurahan' => 'Kalikudi', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 10, 'nama_desa_kelurahan' => 'Karanganyar', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 11, 'nama_desa_kelurahan' => 'Karangbenda', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 12, 'nama_desa_kelurahan' => 'Karangsari', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 13, 'nama_desa_kelurahan' => 'Pedasong', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 14, 'nama_desa_kelurahan' => 'Penggalang', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 15, 'nama_desa_kelurahan' => 'Welahan Wetan', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 16, 'nama_desa_kelurahan' => 'Wlahar', 'id_kecamatan' => 1],
            ['id_desa_kelurahan' => 17, 'nama_desa_kelurahan' => 'Bantarsari', 'id_kecamatan' => 2],
            ['id_desa_kelurahan' => 18, 'nama_desa_kelurahan' => 'Binangun', 'id_kecamatan' => 2],
            ['id_desa_kelurahan' => 19, 'nama_desa_kelurahan' => 'Bulaksari', 'id_kecamatan' => 2],
            ['id_desa_kelurahan' => 20, 'nama_desa_kelurahan' => 'Cikedondong', 'id_kecamatan' => 2],
            ['id_desa_kelurahan' => 21, 'nama_desa_kelurahan' => 'Citembong', 'id_kecamatan' => 2],
            ['id_desa_kelurahan' => 22, 'nama_desa_kelurahan' => 'Kamulyan', 'id_kecamatan' => 2],
            ['id_desa_kelurahan' => 23, 'nama_desa_kelurahan' => 'Kedungwadas', 'id_kecamatan' => 2],
            ['id_desa_kelurahan' => 24, 'nama_desa_kelurahan' => 'Rawajaya', 'id_kecamatan' => 2],
            ['id_desa_kelurahan' => 25, 'nama_desa_kelurahan' => 'Alangamba', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 26, 'nama_desa_kelurahan' => 'Bangkal', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 27, 'nama_desa_kelurahan' => 'Binangun', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 28, 'nama_desa_kelurahan' => 'Jati', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 29, 'nama_desa_kelurahan' => 'Jepara Kulon', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 30, 'nama_desa_kelurahan' => 'Jepara Wetan', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 31, 'nama_desa_kelurahan' => 'Karangnangka', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 32, 'nama_desa_kelurahan' => 'Kemojing', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 33, 'nama_desa_kelurahan' => 'Kepudang', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 34, 'nama_desa_kelurahan' => 'Pagubugan', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 35, 'nama_desa_kelurahan' => 'Pagubugan Kulon', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 36, 'nama_desa_kelurahan' => 'Pasuruhan', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 37, 'nama_desa_kelurahan' => 'Pesawahan', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 38, 'nama_desa_kelurahan' => 'Sidaurip', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 39, 'nama_desa_kelurahan' => 'Sidayu', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 40, 'nama_desa_kelurahan' => 'Widarapayung Kulon', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 41, 'nama_desa_kelurahan' => 'Widarapayung Wetan', 'id_kecamatan' => 3],
            ['id_desa_kelurahan' => 42, 'nama_desa_kelurahan' => 'Cilacap', 'id_kecamatan' => 4],
            ['id_desa_kelurahan' => 43, 'nama_desa_kelurahan' => 'Sidakaya', 'id_kecamatan' => 4],
            ['id_desa_kelurahan' => 44, 'nama_desa_kelurahan' => 'Tambakreja', 'id_kecamatan' => 4],
            ['id_desa_kelurahan' => 45, 'nama_desa_kelurahan' => 'Tegalkamulyan', 'id_kecamatan' => 4],
            ['id_desa_kelurahan' => 46, 'nama_desa_kelurahan' => 'Tegalreja', 'id_kecamatan' => 4],
            ['id_desa_kelurahan' => 47, 'nama_desa_kelurahan' => 'Donan', 'id_kecamatan' => 5],
            ['id_desa_kelurahan' => 48, 'nama_desa_kelurahan' => 'Gunungsimping', 'id_kecamatan' => 5],
            ['id_desa_kelurahan' => 49, 'nama_desa_kelurahan' => 'Kutawaru', 'id_kecamatan' => 5],
            ['id_desa_kelurahan' => 50, 'nama_desa_kelurahan' => 'Lomanis', 'id_kecamatan' => 5],
            ['id_desa_kelurahan' => 51, 'nama_desa_kelurahan' => 'Sidanegara', 'id_kecamatan' => 5],
            ['id_desa_kelurahan' => 52, 'nama_desa_kelurahan' => 'Gumilir', 'id_kecamatan' => 6],
            ['id_desa_kelurahan' => 53, 'nama_desa_kelurahan' => 'Karangtalun', 'id_kecamatan' => 6],
            ['id_desa_kelurahan' => 54, 'nama_desa_kelurahan' => 'Kebonmanis', 'id_kecamatan' => 6],
            ['id_desa_kelurahan' => 55, 'nama_desa_kelurahan' => 'Mertasinga', 'id_kecamatan' => 6],
            ['id_desa_kelurahan' => 56, 'nama_desa_kelurahan' => 'Tritih Kulon', 'id_kecamatan' => 6],
            ['id_desa_kelurahan' => 57, 'nama_desa_kelurahan' => 'Bantarmangu', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 58, 'nama_desa_kelurahan' => 'Bantarpanjang', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 59, 'nama_desa_kelurahan' => 'Cibalung', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 60, 'nama_desa_kelurahan' => 'Cijati', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 61, 'nama_desa_kelurahan' => 'Cilempuyang', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 62, 'nama_desa_kelurahan' => 'Cimanggu', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 63, 'nama_desa_kelurahan' => 'Cisalak', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 64, 'nama_desa_kelurahan' => 'Karangreja', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 65, 'nama_desa_kelurahan' => 'Karangsari', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 66, 'nama_desa_kelurahan' => 'Kutabima', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 67, 'nama_desa_kelurahan' => 'Mandala', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 68, 'nama_desa_kelurahan' => 'Negarajati', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 69, 'nama_desa_kelurahan' => 'Panimbang', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 70, 'nama_desa_kelurahan' => 'Pesahangan', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 71, 'nama_desa_kelurahan' => 'Rejodadi', 'id_kecamatan' => 7],
            ['id_desa_kelurahan' => 72, 'nama_desa_kelurahan' => 'Caruy', 'id_kecamatan' => 8],
            ['id_desa_kelurahan' => 73, 'nama_desa_kelurahan' => 'Cipari', 'id_kecamatan' => 8],
            ['id_desa_kelurahan' => 74, 'nama_desa_kelurahan' => 'Cisuru', 'id_kecamatan' => 8],
            ['id_desa_kelurahan' => 75, 'nama_desa_kelurahan' => 'Karangreja', 'id_kecamatan' => 8],
            ['id_desa_kelurahan' => 76, 'nama_desa_kelurahan' => 'Kutasari', 'id_kecamatan' => 8],
            ['id_desa_kelurahan' => 77, 'nama_desa_kelurahan' => 'Mekarsari', 'id_kecamatan' => 8],
            ['id_desa_kelurahan' => 78, 'nama_desa_kelurahan' => 'Mulyadadi', 'id_kecamatan' => 8],
            ['id_desa_kelurahan' => 79, 'nama_desa_kelurahan' => 'Pegadingan', 'id_kecamatan' => 8],
            ['id_desa_kelurahan' => 80, 'nama_desa_kelurahan' => 'Segaralangu', 'id_kecamatan' => 8],
            ['id_desa_kelurahan' => 81, 'nama_desa_kelurahan' => 'Serang', 'id_kecamatan' => 8],
            ['id_desa_kelurahan' => 82, 'nama_desa_kelurahan' => 'Sidasari', 'id_kecamatan' => 8],
            ['id_desa_kelurahan' => 83, 'nama_desa_kelurahan' => 'Bingkeng', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 84, 'nama_desa_kelurahan' => 'Bolang', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 85, 'nama_desa_kelurahan' => 'Cijeruk', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 86, 'nama_desa_kelurahan' => 'Cilumping', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 87, 'nama_desa_kelurahan' => 'Ciwalen', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 88, 'nama_desa_kelurahan' => 'Datar', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 89, 'nama_desa_kelurahan' => 'Dayeuhluhur', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 90, 'nama_desa_kelurahan' => 'Hanum', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 91, 'nama_desa_kelurahan' => 'Kutaagung', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 92, 'nama_desa_kelurahan' => 'Matenggeng', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 93, 'nama_desa_kelurahan' => 'Panulisan', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 94, 'nama_desa_kelurahan' => 'Panulisan Barat', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 95, 'nama_desa_kelurahan' => 'Panulisan Timur', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 96, 'nama_desa_kelurahan' => 'Sumpinghayu', 'id_kecamatan' => 9],
            ['id_desa_kelurahan' => 97, 'nama_desa_kelurahan' => 'Bulusari', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 98, 'nama_desa_kelurahan' => 'Cinangsi', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 99, 'nama_desa_kelurahan' => 'Cisumur', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 100, 'nama_desa_kelurahan' => 'Gandrungmangu', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 101, 'nama_desa_kelurahan' => 'Gandrungmanis', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 102, 'nama_desa_kelurahan' => 'Gintungreja', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 103, 'nama_desa_kelurahan' => 'Karanganyar', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 104, 'nama_desa_kelurahan' => 'Karanggintung', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 105, 'nama_desa_kelurahan' => 'Kertajaya', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 106, 'nama_desa_kelurahan' => 'Layansari', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 107, 'nama_desa_kelurahan' => 'Muktisari', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 108, 'nama_desa_kelurahan' => 'Rungkang', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 109, 'nama_desa_kelurahan' => 'Sidaurip', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 110, 'nama_desa_kelurahan' => 'Wringinharjo', 'id_kecamatan' => 10],
            ['id_desa_kelurahan' => 111, 'nama_desa_kelurahan' => 'Brebeg', 'id_kecamatan' => 11],
            ['id_desa_kelurahan' => 112, 'nama_desa_kelurahan' => 'Cilibang', 'id_kecamatan' => 11],
            ['id_desa_kelurahan' => 113, 'nama_desa_kelurahan' => 'Citepus', 'id_kecamatan' => 11],
            ['id_desa_kelurahan' => 114, 'nama_desa_kelurahan' => 'Jambusari', 'id_kecamatan' => 11],
            ['id_desa_kelurahan' => 115, 'nama_desa_kelurahan' => 'Jeruklegi Kulon', 'id_kecamatan' => 11],
            ['id_desa_kelurahan' => 116, 'nama_desa_kelurahan' => 'Jeruklegi Wetan', 'id_kecamatan' => 11],
            ['id_desa_kelurahan' => 117, 'nama_desa_kelurahan' => 'Karangkemiri', 'id_kecamatan' => 11],
            ['id_desa_kelurahan' => 118, 'nama_desa_kelurahan' => 'Mandala', 'id_kecamatan' => 11],
            ['id_desa_kelurahan' => 119, 'nama_desa_kelurahan' => 'Prapagan', 'id_kecamatan' => 11],
            ['id_desa_kelurahan' => 120, 'nama_desa_kelurahan' => 'Sawangan', 'id_kecamatan' => 11],
            ['id_desa_kelurahan' => 121, 'nama_desa_kelurahan' => 'Sumingkir', 'id_kecamatan' => 11],
            ['id_desa_kelurahan' => 122, 'nama_desa_kelurahan' => 'Tritih Lor', 'id_kecamatan' => 11],
            ['id_desa_kelurahan' => 123, 'nama_desa_kelurahan' => 'Tritih Wetan', 'id_kecamatan' => 11],
            ['id_desa_kelurahan' => 124, 'nama_desa_kelurahan' => 'Klaces', 'id_kecamatan' => 12],
            ['id_desa_kelurahan' => 125, 'nama_desa_kelurahan' => 'Panikel', 'id_kecamatan' => 12],
            ['id_desa_kelurahan' => 126, 'nama_desa_kelurahan' => 'Ujungalang', 'id_kecamatan' => 12],
            ['id_desa_kelurahan' => 127, 'nama_desa_kelurahan' => 'Ujunggagak', 'id_kecamatan' => 12],
            ['id_desa_kelurahan' => 128, 'nama_desa_kelurahan' => 'Babakan', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 129, 'nama_desa_kelurahan' => 'Bengbulang', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 130, 'nama_desa_kelurahan' => 'Cidadap', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 131, 'nama_desa_kelurahan' => 'Ciporos', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 132, 'nama_desa_kelurahan' => 'Ciruyung', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 133, 'nama_desa_kelurahan' => 'Gunungtelu', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 134, 'nama_desa_kelurahan' => 'Karangpucung', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 135, 'nama_desa_kelurahan' => 'Pamulihan', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 136, 'nama_desa_kelurahan' => 'Pengawaren', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 137, 'nama_desa_kelurahan' => 'Sidamulya', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 138, 'nama_desa_kelurahan' => 'Sindangbarang', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 139, 'nama_desa_kelurahan' => 'Surusunda', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 140, 'nama_desa_kelurahan' => 'Tayem', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 141, 'nama_desa_kelurahan' => 'Tayem Timur', 'id_kecamatan' => 13],
            ['id_desa_kelurahan' => 142, 'nama_desa_kelurahan' => 'Babakan', 'id_kecamatan' => 14],
            ['id_desa_kelurahan' => 143, 'nama_desa_kelurahan' => 'Bojong', 'id_kecamatan' => 14],
            ['id_desa_kelurahan' => 144, 'nama_desa_kelurahan' => 'Bringkeng', 'id_kecamatan' => 14],
            ['id_desa_kelurahan' => 145, 'nama_desa_kelurahan' => 'Grugu', 'id_kecamatan' => 14],
            ['id_desa_kelurahan' => 146, 'nama_desa_kelurahan' => 'Kalijeruk', 'id_kecamatan' => 14],
            ['id_desa_kelurahan' => 147, 'nama_desa_kelurahan' => 'Kawunganten', 'id_kecamatan' => 14],
            ['id_desa_kelurahan' => 148, 'nama_desa_kelurahan' => 'Kawunganten Lor', 'id_kecamatan' => 14],
            ['id_desa_kelurahan' => 149, 'nama_desa_kelurahan' => 'Kubangkangkung', 'id_kecamatan' => 14],
            ['id_desa_kelurahan' => 150, 'nama_desa_kelurahan' => 'Mentasan', 'id_kecamatan' => 14],
            ['id_desa_kelurahan' => 151, 'nama_desa_kelurahan' => 'Sarwadadi', 'id_kecamatan' => 14],
            ['id_desa_kelurahan' => 152, 'nama_desa_kelurahan' => 'Sidaurip', 'id_kecamatan' => 14],
            ['id_desa_kelurahan' => 153, 'nama_desa_kelurahan' => 'Ujungmanik', 'id_kecamatan' => 14],
            ['id_desa_kelurahan' => 154, 'nama_desa_kelurahan' => 'Bangunreja', 'id_kecamatan' => 15],
            ['id_desa_kelurahan' => 155, 'nama_desa_kelurahan' => 'Bojongsari', 'id_kecamatan' => 15],
            ['id_desa_kelurahan' => 156, 'nama_desa_kelurahan' => 'Bumireja', 'id_kecamatan' => 15],
            ['id_desa_kelurahan' => 157, 'nama_desa_kelurahan' => 'Ciklapa', 'id_kecamatan' => 15],
            ['id_desa_kelurahan' => 158, 'nama_desa_kelurahan' => 'Jatisari', 'id_kecamatan' => 15],
            ['id_desa_kelurahan' => 159, 'nama_desa_kelurahan' => 'Kaliwungu', 'id_kecamatan' => 15],
            ['id_desa_kelurahan' => 160, 'nama_desa_kelurahan' => 'Kedungreja', 'id_kecamatan' => 15],
            ['id_desa_kelurahan' => 161, 'nama_desa_kelurahan' => 'Rejamulya', 'id_kecamatan' => 15],
            ['id_desa_kelurahan' => 162, 'nama_desa_kelurahan' => 'Sidanegara', 'id_kecamatan' => 15],
            ['id_desa_kelurahan' => 163, 'nama_desa_kelurahan' => 'Tambakreja', 'id_kecamatan' => 15],
            ['id_desa_kelurahan' => 164, 'nama_desa_kelurahan' => 'Tambaksari', 'id_kecamatan' => 15],
            ['id_desa_kelurahan' => 165, 'nama_desa_kelurahan' => 'Bulupayung', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 166, 'nama_desa_kelurahan' => 'Ciwuni', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 167, 'nama_desa_kelurahan' => 'Dondong', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 168, 'nama_desa_kelurahan' => 'Jangrana', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 169, 'nama_desa_kelurahan' => 'Kalisabuk', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 170, 'nama_desa_kelurahan' => 'Karangjengkol', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 171, 'nama_desa_kelurahan' => 'Karangkandri', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 172, 'nama_desa_kelurahan' => 'Keleng', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 173, 'nama_desa_kelurahan' => 'Kesugihan', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 174, 'nama_desa_kelurahan' => 'Kesugihan Kidul', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 175, 'nama_desa_kelurahan' => 'Kuripan', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 176, 'nama_desa_kelurahan' => 'Kuripan Kidul', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 177, 'nama_desa_kelurahan' => 'Menganti', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 178, 'nama_desa_kelurahan' => 'Pesanggrahan', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 179, 'nama_desa_kelurahan' => 'Planjan', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 180, 'nama_desa_kelurahan' => 'Slarang', 'id_kecamatan' => 16],
            ['id_desa_kelurahan' => 181, 'nama_desa_kelurahan' => 'Ayamalas', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 182, 'nama_desa_kelurahan' => 'Bajing', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 183, 'nama_desa_kelurahan' => 'Bajing Kulon', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 184, 'nama_desa_kelurahan' => 'Buntu', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 185, 'nama_desa_kelurahan' => 'Gentasari', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 186, 'nama_desa_kelurahan' => 'Karangmangu', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 187, 'nama_desa_kelurahan' => 'Karangturi', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 188, 'nama_desa_kelurahan' => 'Kedawung', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 189, 'nama_desa_kelurahan' => 'Kroya', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 190, 'nama_desa_kelurahan' => 'Mergawati', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 191, 'nama_desa_kelurahan' => 'Mujur', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 192, 'nama_desa_kelurahan' => 'Mujur Lor', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 193, 'nama_desa_kelurahan' => 'Pekuncen', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 194, 'nama_desa_kelurahan' => 'Pesanggrahan', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 195, 'nama_desa_kelurahan' => 'Pucung Kidul', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 196, 'nama_desa_kelurahan' => 'Pucung Lor', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 197, 'nama_desa_kelurahan' => 'Sikampuh', 'id_kecamatan' => 17],
            ['id_desa_kelurahan' => 198, 'nama_desa_kelurahan' => 'Bener', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 199, 'nama_desa_kelurahan' => 'Boja', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 200, 'nama_desa_kelurahan' => 'Cibeunying', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 201, 'nama_desa_kelurahan' => 'Cilopadang', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 202, 'nama_desa_kelurahan' => 'Jenang', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 203, 'nama_desa_kelurahan' => 'Mulyadadi', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 204, 'nama_desa_kelurahan' => 'Mulyasari', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 205, 'nama_desa_kelurahan' => 'Padangjaya', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 206, 'nama_desa_kelurahan' => 'Padangsari', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 207, 'nama_desa_kelurahan' => 'Pahonjean', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 208, 'nama_desa_kelurahan' => 'Pengadegan', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 209, 'nama_desa_kelurahan' => 'Sadabumi', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 210, 'nama_desa_kelurahan' => 'Sadahayu', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 211, 'nama_desa_kelurahan' => 'Salebu', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 212, 'nama_desa_kelurahan' => 'Sepatnunggal', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 213, 'nama_desa_kelurahan' => 'Sindangsari', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 214, 'nama_desa_kelurahan' => 'Ujungbarang', 'id_kecamatan' => 18],
            ['id_desa_kelurahan' => 215, 'nama_desa_kelurahan' => 'Glempang', 'id_kecamatan' => 19],
            ['id_desa_kelurahan' => 216, 'nama_desa_kelurahan' => 'Kalijaran', 'id_kecamatan' => 19],
            ['id_desa_kelurahan' => 217, 'nama_desa_kelurahan' => 'Karangkemiri', 'id_kecamatan' => 19],
            ['id_desa_kelurahan' => 218, 'nama_desa_kelurahan' => 'Karangreja', 'id_kecamatan' => 19],
            ['id_desa_kelurahan' => 219, 'nama_desa_kelurahan' => 'Karangrena', 'id_kecamatan' => 19],
            ['id_desa_kelurahan' => 220, 'nama_desa_kelurahan' => 'Klapagada', 'id_kecamatan' => 19],
            ['id_desa_kelurahan' => 221, 'nama_desa_kelurahan' => 'Maos Kidul', 'id_kecamatan' => 19],
            ['id_desa_kelurahan' => 222, 'nama_desa_kelurahan' => 'Maos Lor', 'id_kecamatan' => 19],
            ['id_desa_kelurahan' => 223, 'nama_desa_kelurahan' => 'Mernek', 'id_kecamatan' => 19],
            ['id_desa_kelurahan' => 224, 'nama_desa_kelurahan' => 'Panisihan', 'id_kecamatan' => 19],
            ['id_desa_kelurahan' => 225, 'nama_desa_kelurahan' => 'Danasri', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 226, 'nama_desa_kelurahan' => 'Danasri Kidul', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 227, 'nama_desa_kelurahan' => 'Danasri Lor', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 228, 'nama_desa_kelurahan' => 'Sikanco', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 229, 'nama_desa_kelurahan' => 'Nusawungu', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 230, 'nama_desa_kelurahan' => 'Nusawangkal', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 231, 'nama_desa_kelurahan' => 'Karangpakis', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 232, 'nama_desa_kelurahan' => 'Banjarsari', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 233, 'nama_desa_kelurahan' => 'Jetis', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 234, 'nama_desa_kelurahan' => 'Banjareja', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 235, 'nama_desa_kelurahan' => 'Kedungbenda', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 236, 'nama_desa_kelurahan' => 'Klumprit', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 237, 'nama_desa_kelurahan' => 'Karangsembung', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 238, 'nama_desa_kelurahan' => 'Purwadadi', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 239, 'nama_desa_kelurahan' => 'Karangputat', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 240, 'nama_desa_kelurahan' => 'Banjarwaru', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 241, 'nama_desa_kelurahan' => 'Karangtawang', 'id_kecamatan' => 20],
            ['id_desa_kelurahan' => 242, 'nama_desa_kelurahan' => 'Bulupayung', 'id_kecamatan' => 21],
            ['id_desa_kelurahan' => 243, 'nama_desa_kelurahan' => 'Cimrutu', 'id_kecamatan' => 21],
            ['id_desa_kelurahan' => 244, 'nama_desa_kelurahan' => 'Cinyawang', 'id_kecamatan' => 21],
            ['id_desa_kelurahan' => 245, 'nama_desa_kelurahan' => 'Patimuan', 'id_kecamatan' => 21],
            ['id_desa_kelurahan' => 246, 'nama_desa_kelurahan' => 'Purwodadi', 'id_kecamatan' => 21],
            ['id_desa_kelurahan' => 247, 'nama_desa_kelurahan' => 'Rawaapu', 'id_kecamatan' => 21],
            ['id_desa_kelurahan' => 248, 'nama_desa_kelurahan' => 'Sidamukti', 'id_kecamatan' => 21],
            ['id_desa_kelurahan' => 249, 'nama_desa_kelurahan' => 'Brani', 'id_kecamatan' => 22],
            ['id_desa_kelurahan' => 250, 'nama_desa_kelurahan' => 'Karangasem', 'id_kecamatan' => 22],
            ['id_desa_kelurahan' => 251, 'nama_desa_kelurahan' => 'Karangjati', 'id_kecamatan' => 22],
            ['id_desa_kelurahan' => 252, 'nama_desa_kelurahan' => 'Karangtengah', 'id_kecamatan' => 22],
            ['id_desa_kelurahan' => 253, 'nama_desa_kelurahan' => 'Ketanggung', 'id_kecamatan' => 22],
            ['id_desa_kelurahan' => 254, 'nama_desa_kelurahan' => 'Nusajati', 'id_kecamatan' => 22],
            ['id_desa_kelurahan' => 255, 'nama_desa_kelurahan' => 'Paberasan', 'id_kecamatan' => 22],
            ['id_desa_kelurahan' => 256, 'nama_desa_kelurahan' => 'Paketingan', 'id_kecamatan' => 22],
            ['id_desa_kelurahan' => 257, 'nama_desa_kelurahan' => 'Sampang', 'id_kecamatan' => 22],
            ['id_desa_kelurahan' => 258, 'nama_desa_kelurahan' => 'Sidasari', 'id_kecamatan' => 22],
            ['id_desa_kelurahan' => 259, 'nama_desa_kelurahan' => 'Gunungreja', 'id_kecamatan' => 23],
            ['id_desa_kelurahan' => 260, 'nama_desa_kelurahan' => 'Karanggedang', 'id_kecamatan' => 23],
            ['id_desa_kelurahan' => 261, 'nama_desa_kelurahan' => 'Kunci', 'id_kecamatan' => 23],
            ['id_desa_kelurahan' => 262, 'nama_desa_kelurahan' => 'Margasari', 'id_kecamatan' => 23],
            ['id_desa_kelurahan' => 263, 'nama_desa_kelurahan' => 'Penyarang', 'id_kecamatan' => 23],
            ['id_desa_kelurahan' => 264, 'nama_desa_kelurahan' => 'Sidamulya', 'id_kecamatan' => 23],
            ['id_desa_kelurahan' => 265, 'nama_desa_kelurahan' => 'Sidareja', 'id_kecamatan' => 23],
            ['id_desa_kelurahan' => 266, 'nama_desa_kelurahan' => 'Sudagaran', 'id_kecamatan' => 23],
            ['id_desa_kelurahan' => 267, 'nama_desa_kelurahan' => 'Tegalsari', 'id_kecamatan' => 23],
            ['id_desa_kelurahan' => 268, 'nama_desa_kelurahan' => 'Tinggarjaya', 'id_kecamatan' => 23],
            ['id_desa_kelurahan' => 269, 'nama_desa_kelurahan' => 'Adimulya', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 270, 'nama_desa_kelurahan' => 'Bantar', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 271, 'nama_desa_kelurahan' => 'Cigintung', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 272, 'nama_desa_kelurahan' => 'Cilongkrang', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 273, 'nama_desa_kelurahan' => 'Jambu', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 274, 'nama_desa_kelurahan' => 'Limbangan', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 275, 'nama_desa_kelurahan' => 'Madura', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 276, 'nama_desa_kelurahan' => 'Madusari', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 277, 'nama_desa_kelurahan' => 'Majingklak', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 278, 'nama_desa_kelurahan' => 'Malabar', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 279, 'nama_desa_kelurahan' => 'Palugon', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 280, 'nama_desa_kelurahan' => 'Purwasari', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 281, 'nama_desa_kelurahan' => 'Sidamulya', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 282, 'nama_desa_kelurahan' => 'Tambaksari', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 283, 'nama_desa_kelurahan' => 'Tarisi', 'id_kecamatan' => 24],
            ['id_desa_kelurahan' => 284, 'nama_desa_kelurahan' => 'Wanareja', 'id_kecamatan' => 24],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('desa_kelurahan');
    }
};