@php
    $monitor = request()->routeIs('kadis.persetujuan_bantuan_kube.*', 'kadis.pencairan_bantuan.*', 'kube.*', 'monitoring.*', 'galeri.*');
    $analisis = request()->routeIs('ranking.kube*', 'admin.prediksi-kube.*');
    $arsip = request()->routeIs('kadis.laporan.kecamatan*', 'laporan.*');
    $active = 'bg-indigo-800 text-white shadow-inner'; $inactive = 'text-indigo-100 hover:bg-indigo-600 hover:text-white';
    $subActive = 'bg-indigo-700 text-white border-l-2 border-white'; $subInactive = 'text-indigo-200 hover:bg-indigo-700/60 hover:text-white';
@endphp
<nav class="flex-1 px-4 mt-4 space-y-2 overflow-y-auto custom-scrollbar">
    <a href="{{ route('kadis.dashboard') }}" class="flex items-center gap-3 px-4 py-3 rounded-xl transition-all {{ request()->routeIs('kadis.dashboard', 'dashboard.dinas') ? 'bg-indigo-800 text-white border-l-4 border-white shadow-inner' : $inactive }}"><i data-lucide="pie-chart" class="w-5 h-5"></i><span class="font-medium text-sm">Dashboard Statistik</span></a>
    <div class="relative"><button type="button" onclick="toggleDropdown('monitorDinas', 'monitorIcon')" class="w-full flex items-center justify-between px-4 py-3 rounded-xl transition-all {{ $monitor ? $active : $inactive }}"><span class="flex items-center gap-3"><i data-lucide="eye" class="w-5 h-5"></i><span class="font-medium text-sm">Monitoring Program</span></span><i data-lucide="chevron-down" id="monitorIcon" class="w-4 h-4 transition-transform {{ $monitor ? 'rotate-180' : '' }}"></i></button>
        <div id="monitorDinas" class="{{ $monitor ? '' : 'hidden' }} flex flex-col mt-2 ml-4 space-y-1 border-l border-indigo-500/50 pl-4 text-[11px] uppercase tracking-widest font-bold">
            <a href="{{ route('kadis.persetujuan_bantuan_kube.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('kadis.persetujuan_bantuan_kube.*') ? $subActive : $subInactive }}">Persetujuan KUBE</a><a href="{{ route('kadis.pencairan_bantuan.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('kadis.pencairan_bantuan.*') ? $subActive : $subInactive }}">Pencairan Bantuan</a><a href="{{ route('kube.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('kube.*') ? $subActive : $subInactive }}">Sebaran KUBE</a><a href="{{ route('monitoring.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('monitoring.*') ? $subActive : $subInactive }}">Penggunaan Bantuan</a><a href="{{ route('galeri.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('galeri.*') ? $subActive : $subInactive }}">Galeri Kegiatan</a>
        </div></div>
    <div class="relative"><button type="button" onclick="toggleDropdown('analisisDinas', 'analisisIcon')" class="w-full flex items-center justify-between px-4 py-3 rounded-xl transition-all {{ $analisis ? $active : $inactive }}"><span class="flex items-center gap-3"><i data-lucide="trending-up" class="w-5 h-5"></i><span class="font-medium text-sm">Analisis Performa</span></span><i data-lucide="chevron-down" id="analisisIcon" class="w-4 h-4 transition-transform {{ $analisis ? 'rotate-180' : '' }}"></i></button><div id="analisisDinas" class="{{ $analisis ? '' : 'hidden' }} flex flex-col mt-2 ml-4 space-y-1 border-l border-indigo-500/50 pl-4 text-[11px] uppercase tracking-widest font-bold"><a href="{{ route('ranking.kube') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('ranking.kube*') ? $subActive : $subInactive }}">Ranking KUBE</a><a href="{{ route('admin.prediksi-kube.daftar') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('admin.prediksi-kube.*') ? $subActive : $subInactive }}">Prediksi Kelulusan</a></div></div>
    <div class="relative"><button type="button" onclick="toggleDropdown('docDinas', 'docIcon')" class="w-full flex items-center justify-between px-4 py-3 rounded-xl transition-all {{ $arsip ? $active : $inactive }}"><span class="flex items-center gap-3"><i data-lucide="file-check" class="w-5 h-5"></i><span class="font-medium text-sm">Arsip & Laporan</span></span><i data-lucide="chevron-down" id="docIcon" class="w-4 h-4 transition-transform {{ $arsip ? 'rotate-180' : '' }}"></i></button><div id="docDinas" class="{{ $arsip ? '' : 'hidden' }} flex flex-col mt-2 ml-4 space-y-1 border-l border-indigo-500/50 pl-4 text-[11px] uppercase tracking-widest font-bold"><a href="{{ route('laporan.index') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('laporan.*') ? $subActive : $subInactive }}">Laporan Keuangan Global</a><a href="{{ route('kadis.laporan.kecamatan') }}" class="py-2 px-3 rounded-lg {{ request()->routeIs('kadis.laporan.kecamatan*') ? $subActive : $subInactive }}">Laporan Kecamatan</a></div></div>
</nav>
